[build]
  command = "npm install && npm run build"
  publish = "dist/public"
  base = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

# Build only frontend for static deployment
[build.processing]
  skip_processing = false